// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-WLuXr_5b215ailXAA-SShafurKM5sYw',
    appId: '1:35852590469:web:f46920ea84a9647dad38ec',
    messagingSenderId: '35852590469',
    projectId: 'pawpark-26b38',
    authDomain: 'pawpark-26b38.firebaseapp.com',
    storageBucket: 'pawpark-26b38.firebasestorage.app',
    measurementId: 'G-GR4KG4TG8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfGCPF8XIqv5g9Pkd4qkz3iOPCrP3-iwo',
    appId: '1:35852590469:android:7ba602dc678d7998ad38ec',
    messagingSenderId: '35852590469',
    projectId: 'pawpark-26b38',
    storageBucket: 'pawpark-26b38.firebasestorage.app',
  );
}
